apiVersion: apps/v1
kind: Deployment 
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
     matchLabels:
       app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: img_ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 20
          - containerPort: 21 
          - containerPort: 21000
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb
spec:
  type: LoadBalancer
  selector:
    app: ftps 
  ports:
    - name: ftps-cmd
      protocol: TCP
      port: 21 
    - name: ftps-data
      protocol: TCP
      port: 20 
    - name: ftps-passive
      protocol: TCP
      port: 21000 
  



